osx_image: xcode11.5
language: objective-c
xcode_workspace: PhotoBooth.xcworkspace # path to your xcodeproj folder
xcode_scheme: PhotoBooth
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
